#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'miniMaxSum' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def miniMaxSum(arr):
    sand = []
    for i in range(len(arr)):
        a = arr[0]
        arr.pop(0)
        sum_arr = sum(arr)
        sand.append(sum_arr)
        arr.append(a)
    print(min(sand),max(sand))
if __name__ == '__main__':

    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
